#
# Read openapi.json
# Define general functions
#
# (c) 2025 Jean-Olivier Irisson, GNU General Public License v3

library("jsonlite")

# load API description
api <- fromJSON("https://ecotaxa.obs-vlfr.fr/api/api/openapi.json", simplifyDataFrame=F, simplifyVector=F)
# api <- fromJSON("tools/openapi.json", simplifyDataFrame=F, simplifyVector=F)

# Extract elements from a list, as a vector
get_elements <- function(x, id) { sapply(x, getElement, id) }
gel <- get_elements


#' Print R file
#'
#' @param doc the documentation part of the R file to write. This is a vector of strings with one element per line, each of which will be prepended by a roxygen comments mark (`#'`)
#' @param fun the definition of the function itself: a vector of strings with one element per line.
#' @param out_name the output file name, without the path and without the extension
print_to_R <- function(doc, fun, out_name) {
    out <- c(
    "# Automatically generated. Do not edit this file.",
    str_c("#' ", doc),
    fun
  )
  cat(out, file=str_c("R/", out_name, ".R"), sep="\n")
}
