library("jsonlite")
library("tidyverse")
library("glue")
library("stringr")
library("styler")

## Prepare (load API description, define functions)  ----

# load API description
# api <- fromJSON("https://ecotaxa.obs-vlfr.fr/api/api/openapi.json", simplifyDataFrame=F, simplifyVector=F)
api <- fromJSON("tools/openapi.json", simplifyDataFrame=F, simplifyVector=F)

# Extract elements from a list, as a vector
get_elements <- function(x, id) { sapply(x, getElement, id) }
gel <- get_elements

get_type <- function(x) {
  if (is.null(x$type)) {
    if (!is.null(x$`$ref`)) {
      model <- x$`$ref` %>% str_split("/") %>% pluck(1) %>% tail(1)
      type <- str_c("object of type [", model, "]")
    }
    if (!is.null(x$allOf)) {
      type <- get_type(x$allOf[[1]])
    }
  } else {
    if (x$type == "array") {
      type <- x$items$type
      type <- str_c("vector of ", type)
    } else if (x$type == "object") {
      type <- "list"
    } else (
      type <- x$type
    )
  }
  return(type)
}

get_schema_props <- function(x) {
  required_props <- unlist(x$required)
  props <- imap(x$properties, function(prop, name) {
    prop$name <- name
    prop$required <- name %in% required_props
    prop$type <- get_type(prop)
    if (is.null(prop$title)) {prop$title <- name}
    if (is.null(prop$description)) {prop$description <- prop$title}
    prop$description <- str_replace_all(prop$description, "\n", " ")
    return(prop)
  })
  return(props)
}

wrap_in_list <- function(x) {
  lapply(x, function(.x) {
    if (length(.x) != 1) {.x <- list(.x)}
    return(.x)
  })
}


list_as_tibble <- function(x, ...) {
  el <- list(...)
  lapply(substitute(el), function(.x) {message(.x)})
}

#list_as_tibble(props, foo, bar)

#list_as_tibble <- function(x) {
#  x <- lapply(props, wrap_in_list) %>% lapply(as_tibble_row)
#  bind_rows(x)
#  # elements <- sapply(x, names) %>% unlist() %>% unique()
#  # xl <- lapply(elements, function(el) {
#  #   map(x, pluck, el)
#  # })
#  # names(xl) <- elements
#  # as_tibble(xl)
#}

#list_as_tibble(props)

schemas <- api$components$schemas

iwalk(schemas, function(sch, sch_name) {
  message("  write doc. for ", sch_name)

  props <- get_schema_props(sch)

  doc <- c(
    sch$title,
    "",
    str_c("A list defining a ", sch$title),
    "",
    map_chr(props, glue_data, "@param {name} \\[{type}{ifelse(required, ', required', '')}\\] {description}"),
    "",
    "@export"
  )
  doc <- str_c("#' ", doc)
  # TODO add example

  fun <- c(
    str_c(sch_name, " <- function(",
          str_c(gel(props, "name"), ifelse(gel(props, "required"), "", "=NULL"), collapse=", "),
          ") {"),
    "  body <- list(",
    str_c(map_chr(props, glue_data, "    {name}={name}"), collapse = ",\n"),
    "  )",
    "  body[sapply(body, is.null)] <- NULL",
    "  return(body)",
    "}"
  )

  out <- c(
    "# Automatically generated. Do not edit this file.",
    doc,
    fun
  )
  cat(out, file=str_c("R/", sch_name, ".R"), sep="\n")
})
