# Automatically generated. Do not edit this file.
#' AccessLevelEnum
#' 
#' A vector defining a AccessLevelEnum
#' 
#' @format string containing 1, 2 or 0
#' 
#' @name AccessLevelEnum
#' @export
NULL
