# Automatically generated. Do not edit this file.
#' AcquisitionModel
#' 
#' A list defining a AcquisitionModel
#' 
#' @param acquisid \[integer, required\] The acquisition Id.
#' @param acq_sample_id \[integer, required\] The acquisition sample Id.
#' @param orig_id \[string, required\] Original acquisition ID from initial TSV load.
#' @param instrument \[string\] Instrument used.
#' @param free_columns \[list\] Free columns from acquisition mapping in project.
#' 
#' @export
AcquisitionModel <- function(acquisid, acq_sample_id, orig_id, instrument=NULL, free_columns=NULL) {
  body <- list(
    acquisid=acquisid,
    acq_sample_id=acq_sample_id,
    orig_id=orig_id,
    instrument=instrument,
    free_columns=free_columns
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
