# Automatically generated. Do not edit this file.
#' AddWormsTaxonModel
#' 
#' A list defining a AddWormsTaxonModel
#' 
#' @param aphia_id \[integer\] The unique numeric aphia_id of the taxon in WoRMS.
#' 
#' @export
AddWormsTaxonModel <- function(aphia_id=NULL) {
  body <- list(
    aphia_id=aphia_id
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
