# Automatically generated. Do not edit this file.
#' Backup Export request Model
#' 
#' A list defining a Backup Export request Model
#' 
#' @param project_id \[integer, required\] The project to export.
#' @param out_to_ftp \[boolean\] Copy result file to FTP area. Original file is still available.
#' 
#' @export
BackupExportReq <- function(project_id, out_to_ftp=NULL) {
  body <- list(
    project_id=project_id,
    out_to_ftp=out_to_ftp
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
