# Automatically generated. Do not edit this file.
#' Body_remove_file_user_files_rm__post
#' 
#' A list defining a Body_remove_file_user_files_rm__post
#' 
#' @param source_path \[string\] The path of the file  or directory to be removed. * for all files and directories
#' 
#' @export
Body_remove_file_user_files_rm__post <- function(source_path=NULL) {
  body <- list(
    source_path=source_path
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
