# Automatically generated. Do not edit this file.
#' Body_put_user_file_my_files__post
#' 
#' A list defining a Body_put_user_file_my_files__post
#' 
#' @param file \[string, required\] File
#' @param path \[string\] The client-side full path of the file.
#' @param tag \[string\] If a tag is provided, then all files with the same tag are grouped (in a sub-directory). Otherwise, a temp directory with only this file will be created.
#' 
#' @export
Body_put_user_file_my_files__post <- function(file, path=NULL, tag=NULL) {
  body <- list(
    file=file,
    path=path,
    tag=tag
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
