# Automatically generated. Do not edit this file.
#' Body_put_my_file_user_files__post
#' 
#' A list defining a Body_put_my_file_user_files__post
#' 
#' @param file \[string, required\] File
#' @param path \[string\] The destination path of the file.
#' 
#' @export
Body_put_my_file_user_files__post <- function(file, path=NULL) {
  body <- list(
    file=curl::form_file(file),
    path=path
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
