# Automatically generated. Do not edit this file.
#' Body_create_user_file_user_files_create__post
#' 
#' A list defining a Body_create_user_file_user_files_create__post
#' 
#' @param source_path \[string\] The path of the file or directory to be created.
#' 
#' @export
Body_create_user_file_user_files_create__post <- function(source_path=NULL) {
  body <- list(
    source_path=source_path
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
