# Automatically generated. Do not edit this file.
#' Body_export_object_set_general_object_set_export_general_post
#' 
#' A list defining a Body_export_object_set_general_object_set_export_general_post
#' 
#' @param filters \[object of type [ProjectFilters], required\] filters
#' @param request \[object of type [GeneralExportReq], required\] request
#' 
#' @export
Body_export_object_set_general_object_set_export_general_post <- function(filters, request) {
  body <- list(
    filters=filters,
    request=request
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
