# Automatically generated. Do not edit this file.
#' Body_predict_object_set_object_set_predict_post
#' 
#' A list defining a Body_predict_object_set_object_set_predict_post
#' 
#' @param filters \[object of type [ProjectFilters], required\] filters
#' @param request \[object of type [PredictionReq], required\] request
#' 
#' @export
Body_predict_object_set_object_set_predict_post <- function(filters, request) {
  body <- list(
    filters=filters,
    request=request
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
