# Automatically generated. Do not edit this file.
#' Body_move_file_user_files_mv__post
#' 
#' A list defining a Body_move_file_user_files_mv__post
#' 
#' @param source_path \[string\] The  path of the file or directory to be moved.
#' @param dest_path \[string\] The path of the destination file or directory.
#' 
#' @export
Body_move_file_user_files_mv__post <- function(source_path=NULL, dest_path=NULL) {
  body <- list(
    source_path=source_path,
    dest_path=dest_path
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
