# Automatically generated. Do not edit this file.
#' Body_export_object_set_object_set_export_post
#' 
#' A list defining a Body_export_object_set_object_set_export_post
#' 
#' @param filters \[object of type [ProjectFilters], required\] filters
#' @param request \[object of type [ExportReq], required\] Request
#' 
#' @export
Body_export_object_set_object_set_export_post <- function(filters, request) {
  body <- list(
    filters=filters,
    request=request
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
