# Automatically generated. Do not edit this file.
#' Classify auto request Model
#' 
#' A list defining a Classify auto request Model
#' 
#' @param target_ids \[vector of integer, required\] The IDs of the target objects.
#' @param classifications \[vector of integer, required\] The wanted new classifications, i.e. taxon ID, one for each object.
#' @param scores \[vector of number, required\] The classification score is generally between 0 and 1. It indicates the probability that the taxon prediction of this object is correct.
#' @param keep_log \[boolean, required\] Set if former automatic classification history is needed.
#' 
#' @export
ClassifyAutoReq <- function(target_ids, classifications, scores, keep_log) {
  body <- list(
    target_ids=target_ids,
    classifications=classifications,
    scores=scores,
    keep_log=keep_log
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
