# Automatically generated. Do not edit this file.
#' ClassifyReq
#' 
#' A list defining a ClassifyReq
#' 
#' @param target_ids \[vector of integer, required\] The IDs of the target objects.
#' @param classifications \[vector of integer, required\] The wanted new classifications, i.e. taxon ID, one for each object. Use -1 to keep present one.
#' @param wanted_qualification \[string, required\] The wanted qualifications for all objects. 'V' or 'P'.
#' 
#' @export
ClassifyReq <- function(target_ids, classifications, wanted_qualification) {
  body <- list(
    target_ids=target_ids,
    classifications=classifications,
    wanted_qualification=wanted_qualification
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
