# Automatically generated. Do not edit this file.
#' CollectionAggregatedRsp
#' 
#' A list defining a CollectionAggregatedRsp
#' 
#' @param can_be_administered \[boolean\] Whether the current user is manager of all collection projects
#' @param instrument \[string\] The collection instrument from projects.
#' @param access \[object of type [AccessLevelEnum]\] The restricted access for collection projects.PUBLIC: "1", OPEN: "2", PRIVATE: "0"
#' @param initclassiflist \[string, required\]  Aggregated categories from the collection projects.
#' @param classiffieldlist \[string, required\]  Aggregated sorting and displaying fields from the collection projects.
#' @param cnn_network_id \[string, required\]  Common deep features for the collection projects. Can be None (???)
#' @param status \[string, required\]  the restricted collection status calculated from projects.
#' @param creator_users \[vector of \] Annotators extracted from history.
#' @param privileges \[list\] Aggregated user privileges of projects with user minimal right on projects
#' @param freecols \[list\] Common free cols of projects.
#' @param excluded \[list\] Excluded projects for common values 
#' 
#' @export
CollectionAggregatedRsp <- function(can_be_administered=NULL, instrument=NULL, access=NULL, initclassiflist, classiffieldlist, cnn_network_id, status, creator_users=NULL, privileges=NULL, freecols=NULL, excluded=NULL) {
  body <- list(
    can_be_administered=can_be_administered,
    instrument=instrument,
    access=access,
    initclassiflist=initclassiflist,
    classiffieldlist=classiffieldlist,
    cnn_network_id=cnn_network_id,
    status=status,
    creator_users=creator_users,
    privileges=privileges,
    freecols=freecols,
    excluded=excluded
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
