# Automatically generated. Do not edit this file.
#' Update request Model
#' 
#' A list defining a Update request Model
#' 
#' @param ucol \[string, required\] Ucol
#' @param uval \[string, required\] Uval
#' 
#' @export
ColUpdate <- function(ucol, uval) {
  body <- list(
    ucol=ucol,
    uval=uval
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
