# Automatically generated. Do not edit this file.
#' Constants
#' 
#' A list defining a Constants
#' 
#' @param license_texts \[list\] The supported licenses and help text/links.
#' @param app_manager \[vector of string\] The application manager identity (name, mail), from config file.
#' @param countries \[vector of string\] List of known countries names.
#' 
#' @export
Constants <- function(license_texts=NULL, app_manager=NULL, countries=NULL) {
  body <- list(
    license_texts=license_texts,
    app_manager=app_manager,
    countries=countries
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
