# Automatically generated. Do not edit this file.
#' Create project request Model
#' 
#' A list defining a Create project request Model
#' 
#' @param clone_of_id \[integer\] Internal, numeric id of a project to clone as a new one. By default it does not clone anything.
#' @param title \[string, required\] The project title, as text.
#' @param instrument \[string\] The project instrument.
#' @param visible \[boolean\] When TRUE, the project is created visible by all users.
#' 
#' @export
CreateProjectReq <- function(clone_of_id=NULL, title, instrument=NULL, visible=NULL) {
  body <- list(
    clone_of_id=clone_of_id,
    title=title,
    instrument=instrument,
    visible=visible
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
