# Automatically generated. Do not edit this file.
#' Create collection request Model
#' 
#' A list defining a Create collection request Model
#' 
#' @param title \[string, required\] The collection title.
#' @param project_ids \[vector of integer, required\] The list of composing project IDs.
#' 
#' @export
CreateCollectionReq <- function(title, project_ids) {
  body <- list(
    title=title,
    project_ids=project_ids
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
