# Automatically generated. Do not edit this file.
#' DarwinCoreExportReq
#' 
#' A list defining a DarwinCoreExportReq
#' 
#' @param collection_id \[integer, required\] The collection to export, by its internal Id.
#' @param dry_run \[boolean\] If set, then only a diagnostic of doability will be done.
#' @param include_predicted \[boolean\] If set, then predicted objects, as well as validated ones, will be exported. A validation status will allow to distinguish between the two possible statuses.
#' @param with_absent \[boolean\] If set, then *absent* records will be generated, in the relevant samples, for categories present in other samples.
#' @param with_computations \[vector of \] Compute organisms abundances (ABO), concentrations (CNC) or biovolumes (BIV). Several possible.
#' @param computations_pre_mapping \[list\] Mapping from present taxon (key) to output replacement one (value), during computations. Use a 0 replacement to _discard_ the objects with present taxon. Note: These are EcoTaxa categories, WoRMS mapping happens after, whatever.
#' @param formulae \[list\] Transitory: How to get values from DB free columns. Python syntax, prefixes are 'sam', 'ssm' and 'obj'. Variables used in computations are 'total_water_volume', 'subsample_coef' and 'individual_volume'
#' @param extra_xml \[vector of string\] XML blocks which will be output, reformatted, inside the <dataset> tag of produced EML. Formal schema is in dataset section of: https://eml.ecoinformatics.org/schema/eml_xsd 
#' 
#' @export
DarwinCoreExportReq <- function(collection_id, dry_run=NULL, include_predicted=NULL, with_absent=NULL, with_computations=NULL, computations_pre_mapping=NULL, formulae=NULL, extra_xml=NULL) {
  body <- list(
    collection_id=collection_id,
    dry_run=dry_run,
    include_predicted=include_predicted,
    with_absent=with_absent,
    with_computations=with_computations,
    computations_pre_mapping=computations_pre_mapping,
    formulae=formulae,
    extra_xml=extra_xml
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
