# Automatically generated. Do not edit this file.
#' DarwinCoreExportReq
#' 
#' A list defining a DarwinCoreExportReq
#' 
#' @param collection_id \[integer, required\] The collection to export, by its internal Id.
#' @param dry_run \[boolean\] If set, then only a diagnostic of doability will be done.
#' @param pre_mapping \[list\] Mapping from present taxon (key) to output replacement one (value). Use a null replacement to _discard_ the present taxon. Note: These are EcoTaxa categories, WoRMS mapping happens after, whatever.
#' @param include_predicted \[boolean\] If set, then predicted objects, as well as validated ones, will be exported. A validation status will allow to distinguish between the two possible statuses.
#' @param with_absent \[boolean\] If set, then *absent* records will be generated, in the relevant samples, for categories present in other samples.
#' @param with_computations \[vector of \] Compute organisms abundances (ABO), concentrations (CNC) or biovolumes (BIV). Several possible.
#' @param formulae \[list\] Transitory: How to get values from DB free columns. Python syntax, prefixes are 'sam', 'ssm' and 'obj'. Variables used in computations are 'total_water_volume', 'subsample_coef' and 'individual_volume'
#' 
#' @export
DarwinCoreExportReq <- function(collection_id, dry_run=NULL, pre_mapping=NULL, include_predicted=NULL, with_absent=NULL, with_computations=NULL, formulae=NULL) {
  body <- list(
    collection_id=collection_id,
    dry_run=dry_run,
    pre_mapping=pre_mapping,
    include_predicted=include_predicted,
    with_absent=with_absent,
    with_computations=with_computations,
    formulae=formulae
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
