# Automatically generated. Do not edit this file.
#' DirectoryEntryModel
#' 
#' A list defining a DirectoryEntryModel
#' 
#' @param name \[string, required\] atomic entry name.
#' @param type \[string, required\] entry type, 'D' for directory, 'F' for file.
#' @param size \[integer, required\] Entry size, for zips.
#' @param mtime \[string, required\] Modification time, in ISO format.
#' 
#' @export
DirectoryEntryModel <- function(name, type, size, mtime) {
  body <- list(
    name=name,
    type=type,
    size=size,
    mtime=mtime
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
