# Automatically generated. Do not edit this file.
#' DirectoryModel
#' 
#' A list defining a DirectoryModel
#' 
#' @param path \[string, required\] A /-separated path from root to this directory.
#' @param entries \[vector of , required\] Entries, i.e. subdirectories or contained files.All entries are readable, i.e. can be used as input or navigated into.
#' 
#' @export
DirectoryModel <- function(path, entries) {
  body <- list(
    path=path,
    entries=entries
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
