# Automatically generated. Do not edit this file.
#' ExportTypeEnum
#' 
#' A vector defining a ExportTypeEnum
#' 
#' @format string containing TSV, BAK, DOI, SUM, ABO, CNC or BIV
#' 
#' @name ExportTypeEnum
#' @export
NULL
