# Automatically generated. Do not edit this file.
#' ExportSplitOptionsEnum
#' 
#' A vector defining a ExportSplitOptionsEnum
#' 
#' @format string containing sample, acquisition, taxon or none
#' 
#' @name ExportSplitOptionsEnum
NULL
