# Automatically generated. Do not edit this file.
#' ExportTypeEnum
#' 
#' A list defining a ExportTypeEnum
#' 
#' 
#' @export
ExportTypeEnum <- function() {
  body <- list(

  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
