# Automatically generated. Do not edit this file.
#' ExportSplitOptionsEnum
#' 
#' A list defining a ExportSplitOptionsEnum
#' 
#' 
#' @export
ExportSplitOptionsEnum <- function() {
  body <- list(

  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
