# Automatically generated. Do not edit this file.
#' ExportRsp
#' 
#' A list defining a ExportRsp
#' 
#' @param errors \[vector of string\] Showstopper problems found preventing building the archive.
#' @param warnings \[vector of string\] Problems found while building the archive, which do not prevent producing it.
#' @param job_id \[integer\] The created job, 0 if there were problems.
#' 
#' @export
ExportRsp <- function(errors=NULL, warnings=NULL, job_id=NULL) {
  body <- list(
    errors=errors,
    warnings=warnings,
    job_id=job_id
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
