# Automatically generated. Do not edit this file.
#' General Export request Model
#' 
#' A list defining a General Export request Model
#' 
#' @param project_id \[integer, required\] The project to export.
#' @param split_by \[object of type [ExportSplitOptionsEnum]\] If not none, separate (in ZIP sub-directories) output per given field.
#' @param with_images \[object of type [ExportImagesOptionsEnum]\] Add in ZIP first (i.e. visible) image, all images, or no image.⚠️ 'all' means maybe several lines per object in TSVs.
#' @param with_internal_ids \[boolean\] Export internal database IDs.
#' @param with_types_row \[boolean\] Add an EcoTaxa-compatible second line with types.
#' @param only_annotations \[boolean\] Only save objects' last annotation data.
#' @param out_to_ftp \[boolean\] Copy result file to FTP area. Original file is still available.
#' 
#' @export
GeneralExportReq <- function(project_id, split_by=NULL, with_images=NULL, with_internal_ids=NULL, with_types_row=NULL, only_annotations=NULL, out_to_ftp=NULL) {
  body <- list(
    project_id=project_id,
    split_by=split_by,
    with_images=with_images,
    with_internal_ids=with_internal_ids,
    with_types_row=with_types_row,
    only_annotations=only_annotations,
    out_to_ftp=out_to_ftp
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
