# Automatically generated. Do not edit this file.
#' GroupDefinitions
#' 
#' A list defining a GroupDefinitions
#' 
#' 
#' @export
GroupDefinitions <- function() {
  body <- list(

  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
