# Automatically generated. Do not edit this file.
#' GuestModel
#' 
#' A list defining a GuestModel
#' 
#' @param id \[integer, required\] The unique numeric id of this user.
#' @param email \[string, required\] User's email address, as text, used during registration.
#' @param name \[string, required\] User's full name, as text.
#' @param country \[string\] The country name, as text (but chosen in a consistent list).
#' @param orcid \[string\] The orcid id https://support.orcid.org.
#' @param organisation \[string, required\] User's organisation name, as text.
#' 
#' @export
GuestModel <- function(id, email, name, country=NULL, orcid=NULL, organisation) {
  body <- list(
    id=id,
    email=email,
    name=name,
    country=country,
    orcid=orcid,
    organisation=organisation
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
