# Automatically generated. Do not edit this file.
#' HistoricalClassification
#' 
#' A list defining a HistoricalClassification
#' 
#' @param objid \[integer\] The object Id.
#' @param classif_id \[integer\] The classification Id.
#' @param classif_date \[string\] The classification date.
#' @param classif_who \[integer\] The user who manualy classify this object.
#' @param classif_type \[string\] The type of classification. Could be **A** for Automatic or **M** for Manual.
#' @param classif_qual \[string\] The classification qualification. Could be **P** for predicted, **V** for validated or **D** for Dubious.
#' @param classif_score \[number\] The classification score is generally between 0 and 1. This is a confidence score, in the fact that, the taxon prediction for this object is correct.
#' @param user_name \[string\] The name of the user who classified this object.
#' @param taxon_name \[string\] The taxon name of the object.
#' 
#' @export
HistoricalClassification <- function(objid=NULL, classif_id=NULL, classif_date=NULL, classif_who=NULL, classif_type=NULL, classif_qual=NULL, classif_score=NULL, user_name=NULL, taxon_name=NULL) {
  body <- list(
    objid=objid,
    classif_id=classif_id,
    classif_date=classif_date,
    classif_who=classif_who,
    classif_type=classif_type,
    classif_qual=classif_qual,
    classif_score=classif_score,
    user_name=user_name,
    taxon_name=taxon_name
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
