# Automatically generated. Do not edit this file.
#' HTTPValidationError
#' 
#' A list defining a HTTPValidationError
#' 
#' @param detail \[vector of \] Detail
#' 
#' @export
HTTPValidationError <- function(detail=NULL) {
  body <- list(
    detail=detail
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
