# Automatically generated. Do not edit this file.
#' ImportRsp
#' 
#' A list defining a ImportRsp
#' 
#' @param job_id \[integer, required\] The job which was created for the run.
#' @param errors \[vector of string\] Errors from analysis.
#' 
#' @export
ImportRsp <- function(job_id, errors=NULL) {
  body <- list(
    job_id=job_id,
    errors=errors
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
