# Automatically generated. Do not edit this file.
#' Import request Model
#' 
#' A list defining a Import request Model
#' 
#' @param source_path \[string, required\] Source path on server, to zip or plain directory.     The path can be returned by a file upload (absolute),     otherwise it's relative to shared file area root.
#' @param taxo_mappings \[list\] Optional taxonomy mapping, the key specifies the taxonomy ID found in file and the value specifies the final taxonomy ID to write.
#' @param skip_loaded_files \[boolean\] If true skip loaded files, else don't.
#' @param skip_existing_objects \[boolean\] If true skip existing objects, else don't.
#' @param update_mode \[string\] Update data ('Yes'), including classification ('Cla').
#' 
#' @export
ImportReq <- function(source_path, taxo_mappings=NULL, skip_loaded_files=NULL, skip_existing_objects=NULL, update_mode=NULL) {
  body <- list(
    source_path=source_path,
    taxo_mappings=taxo_mappings,
    skip_loaded_files=skip_loaded_files,
    skip_existing_objects=skip_existing_objects,
    update_mode=update_mode
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
