# Automatically generated. Do not edit this file.
#' LicenseEnum
#' 
#' A list defining a LicenseEnum
#' 
#' 
#' @export
LicenseEnum <- function() {
  body <- list(

  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
