# Automatically generated. Do not edit this file.
#' LicenseEnum
#' 
#' A vector defining a LicenseEnum
#' 
#' @format string containing CC0 1.0, CC BY 4.0, CC BY-NC 4.0, Copyright or 
#' 
#' @name LicenseEnum
NULL
