# Automatically generated. Do not edit this file.
#' LimitMethods
#' 
#' A list defining a LimitMethods
#' 
#' 
#' @export
LimitMethods <- function() {
  body <- list(

  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
