# Automatically generated. Do not edit this file.
#' Login request Model
#' 
#' A list defining a Login request Model
#' 
#' @param password \[string, required\] User password.
#' @param username \[string, required\] User email used during registration.
#' 
#' @export
LoginReq <- function(password, username) {
  body <- list(
    password=password,
    username=username
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
