# Automatically generated. Do not edit this file.
#' MergeRsp
#' 
#' A list defining a MergeRsp
#' 
#' @param errors \[vector of string\] The errors found during processing.
#' 
#' @export
MergeRsp <- function(errors=NULL) {
  body <- list(
    errors=errors
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
