# Automatically generated. Do not edit this file.
#' MinimalCollectionBO
#' 
#' A list defining a MinimalCollectionBO
#' 
#' @param id \[integer, required\] Id
#' @param external_id \[string\] External Id
#' @param title \[string, required\] Title
#' @param short_title \[string\] Short Title
#' @param provider_user \[integer, required\] Provider User
#' @param contact_user \[integer\] Contact User
#' @param project_ids \[vector of integer, required\] Project Ids
#' 
#' @export
MinimalCollectionBO <- function(id, external_id=NULL, title, short_title=NULL, provider_user, contact_user=NULL, project_ids) {
  body <- list(
    id=id,
    external_id=external_id,
    title=title,
    short_title=short_title,
    provider_user=provider_user,
    contact_user=contact_user,
    project_ids=project_ids
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
