# Automatically generated. Do not edit this file.
#' MinimalUserBO
#' 
#' A list defining a MinimalUserBO
#' 
#' @param id \[integer\] Id
#' @param name \[string\] Name
#' 
#' @export
MinimalUserBO <- function(id=NULL, name=NULL) {
  body <- list(
    id=id,
    name=name
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
