# Automatically generated. Do not edit this file.
#' MLModel
#' 
#' A list defining a MLModel
#' 
#' @param name \[string, required\] A usable model for features extraction.
#' 
#' @export
MLModel <- function(name) {
  body <- list(
    name=name
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
