# Automatically generated. Do not edit this file.
#' ObjectSetQueryRsp
#' 
#' A list defining a ObjectSetQueryRsp
#' 
#' @param object_ids \[vector of integer\] Matching object IDs.
#' @param acquisition_ids \[vector of integer\] Parent (acquisition) IDs.
#' @param sample_ids \[vector of integer\] Parent (sample) IDs.
#' @param project_ids \[vector of integer\] Project Ids.
#' @param details \[vector of array\] Requested fields, in request order.
#' @param total_ids \[integer\] Total rows returned by the query, even if it was window-ed.
#' 
#' @export
ObjectSetQueryRsp <- function(object_ids=NULL, acquisition_ids=NULL, sample_ids=NULL, project_ids=NULL, details=NULL, total_ids=NULL) {
  body <- list(
    object_ids=object_ids,
    acquisition_ids=acquisition_ids,
    sample_ids=sample_ids,
    project_ids=project_ids,
    details=details,
    total_ids=total_ids
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
