# Automatically generated. Do not edit this file.
#' ObjectSetRevertToHistoryRsp
#' 
#' A list defining a ObjectSetRevertToHistoryRsp
#' 
#' @param last_entries \[vector of \] Object + last classification
#' @param classif_info \[list\] Classification names (self+parent) for involved IDs.
#' 
#' @export
ObjectSetRevertToHistoryRsp <- function(last_entries=NULL, classif_info=NULL) {
  body <- list(
    last_entries=last_entries,
    classif_info=classif_info
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
