# Automatically generated. Do not edit this file.
#' ObjectSetSummaryRsp
#' 
#' A list defining a ObjectSetSummaryRsp
#' 
#' @param total_objects \[integer\] Total number of objects in the set.
#' @param validated_objects \[integer\] Number of validated objects in the set.
#' @param dubious_objects \[integer\] Number of dubious objects in the set.
#' @param predicted_objects \[integer\] Number of predicted objects in the set.
#' 
#' @export
ObjectSetSummaryRsp <- function(total_objects=NULL, validated_objects=NULL, dubious_objects=NULL, predicted_objects=NULL) {
  body <- list(
    total_objects=total_objects,
    validated_objects=validated_objects,
    dubious_objects=dubious_objects,
    predicted_objects=predicted_objects
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
