# Automatically generated. Do not edit this file.
#' OrganizationModel
#' 
#' A list defining a OrganizationModel
#' 
#' @param id \[integer, required\] OrganizationIDT unique identifier.
#' @param name \[string, required\] Organization's full name, as text.
#' @param directories \[string\] References to official directories where the organization is referenced, separated by ,.
#' 
#' @export
OrganizationModel <- function(id, name, directories=NULL) {
  body <- list(
    id=id,
    name=name,
    directories=directories
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
