# Automatically generated. Do not edit this file.
#' PredictionInfoT
#' 
#' A list defining a PredictionInfoT
#' 
#' @param object_id \[integer, required\] Object Id
#' @param classif_id \[integer, required\] Classif Id
#' @param score \[number, required\] Score
#' 
#' @export
PredictionInfoT <- function(object_id, classif_id, score) {
  body <- list(
    object_id=object_id,
    classif_id=classif_id,
    score=score
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
