# Automatically generated. Do not edit this file.
#' PredictionInfoRsp
#' 
#' A list defining a PredictionInfoRsp
#' 
#' @param result \[vector of array\] List of lists [object ID, category ID, score for category].
#' 
#' @export
PredictionInfoRsp <- function(result=NULL) {
  body <- list(
    result=result
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
