# Automatically generated. Do not edit this file.
#' ProcessModel
#' 
#' A list defining a ProcessModel
#' 
#' @param processid \[integer, required\] The process Id.
#' @param orig_id \[string, required\] Original process ID from initial TSV load.
#' @param free_columns \[list\] Free columns from process mapping in project
#' 
#' @export
ProcessModel <- function(processid, orig_id, free_columns=NULL) {
  body <- list(
    processid=processid,
    orig_id=orig_id,
    free_columns=free_columns
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
