# Automatically generated. Do not edit this file.
#' ProjectColumnsModel
#' 
#' A list defining a ProjectColumnsModel
#' 
#' @param projid \[integer\] Project ID from the call.
#' @param columns \[vector of string\] Column names from the call.
#' @param values \[vector of string\] All rows regardless of emptiness.
#' 
#' @export
ProjectColumnsModel <- function(projid=NULL, columns=NULL, values=NULL) {
  body <- list(
    projid=projid,
    columns=columns,
    values=values
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
