# Automatically generated. Do not edit this file.
#' ProjectSummaryModel
#' 
#' A list defining a ProjectSummaryModel
#' 
#' @param projid \[integer, required\] Project unique identifier.
#' @param title \[string, required\] Project's title.
#' 
#' @export
ProjectSummaryModel <- function(projid, title) {
  body <- list(
    projid=projid,
    title=title
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
