# Automatically generated. Do not edit this file.
#' ProjectUserStatsModel
#' 
#' A list defining a ProjectUserStatsModel
#' 
#' @param projid \[integer\] The project id.
#' @param annotators \[vector of \] The users who ever decided on classification or state of objects.
#' @param activities \[vector of \] More details on annotators' activities.
#' 
#' @export
ProjectUserStatsModel <- function(projid=NULL, annotators=NULL, activities=NULL) {
  body <- list(
    projid=projid,
    annotators=annotators,
    activities=activities
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
