# Automatically generated. Do not edit this file.
#' Subset request Model
#' 
#' A list defining a Subset request Model
#' 
#' @param taxo \[string\] Taxo
#' @param taxochild \[string\] Taxochild
#' @param statusfilter \[string\] Statusfilter
#' @param MapN \[string\] Mapn
#' @param MapW \[string\] Mapw
#' @param MapE \[string\] Mape
#' @param MapS \[string\] Maps
#' @param depthmin \[string\] Depthmin
#' @param depthmax \[string\] Depthmax
#' @param samples \[string\] Samples
#' @param instrum \[string\] Instrum
#' @param daytime \[string\] Daytime
#' @param month \[string\] Month
#' @param fromdate \[string\] Fromdate
#' @param todate \[string\] Todate
#' @param fromtime \[string\] Fromtime
#' @param totime \[string\] Totime
#' @param inverttime \[string\] Inverttime
#' @param validfromdate \[string\] Validfromdate
#' @param validtodate \[string\] Validtodate
#' @param freenum \[string\] Freenum
#' @param freenumst \[string\] Freenumst
#' @param freenumend \[string\] Freenumend
#' @param freetxt \[string\] Freetxt
#' @param freetxtval \[string\] Freetxtval
#' @param filt_annot \[string\] Filt Annot
#' @param filt_last_annot \[string\] Filt Last Annot
#' 
#' @export
ProjectFiltersDict <- function(taxo=NULL, taxochild=NULL, statusfilter=NULL, MapN=NULL, MapW=NULL, MapE=NULL, MapS=NULL, depthmin=NULL, depthmax=NULL, samples=NULL, instrum=NULL, daytime=NULL, month=NULL, fromdate=NULL, todate=NULL, fromtime=NULL, totime=NULL, inverttime=NULL, validfromdate=NULL, validtodate=NULL, freenum=NULL, freenumst=NULL, freenumend=NULL, freetxt=NULL, freetxtval=NULL, filt_annot=NULL, filt_last_annot=NULL) {
  body <- list(
    taxo=taxo,
    taxochild=taxochild,
    statusfilter=statusfilter,
    MapN=MapN,
    MapW=MapW,
    MapE=MapE,
    MapS=MapS,
    depthmin=depthmin,
    depthmax=depthmax,
    samples=samples,
    instrum=instrum,
    daytime=daytime,
    month=month,
    fromdate=fromdate,
    todate=todate,
    fromtime=fromtime,
    totime=totime,
    inverttime=inverttime,
    validfromdate=validfromdate,
    validtodate=validtodate,
    freenum=freenum,
    freenumst=freenumst,
    freenumend=freenumend,
    freetxt=freetxt,
    freetxtval=freetxtval,
    filt_annot=filt_annot,
    filt_last_annot=filt_last_annot
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
