# Automatically generated. Do not edit this file.
#' ProjectSetColumnStatsModel
#' 
#' A list defining a ProjectSetColumnStatsModel
#' 
#' @param proj_ids \[vector of integer\] Projects IDs from the call.
#' @param total \[integer\] All rows regardless of emptiness.
#' @param columns \[vector of string\] Column names from the call.
#' @param counts \[vector of integer\] Counts of non-empty values, one per column.
#' @param variances \[vector of number\] Variances of values, one per column.
#' 
#' @export
ProjectSetColumnStatsModel <- function(proj_ids=NULL, total=NULL, columns=NULL, counts=NULL, variances=NULL) {
  body <- list(
    proj_ids=proj_ids,
    total=total,
    columns=columns,
    counts=counts,
    variances=variances
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
