# Automatically generated. Do not edit this file.
#' ResetPasswordReq
#' 
#' A list defining a ResetPasswordReq
#' 
#' @param id \[integer\] User unique identifier.
#' @param email \[string\] Email
#' @param password \[string\] Password
#' 
#' @export
ResetPasswordReq <- function(id=NULL, email=NULL, password=NULL) {
  body <- list(
    id=id,
    email=email,
    password=password
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
