# Automatically generated. Do not edit this file.
#' SampleTaxoStatsModel
#' 
#' A list defining a SampleTaxoStatsModel
#' 
#' @param sample_id \[integer\] The sample id.
#' @param used_taxa \[vector of integer\] The taxa/category ids used inside the sample. -1 for unclassified objects.
#' @param nb_unclassified \[integer\] The number of unclassified objects inside the sample.
#' @param nb_validated \[integer\] The number of validated objects inside the sample.
#' @param nb_dubious \[integer\] The number of dubious objects inside the sample.
#' @param nb_predicted \[integer\] The number of predicted objects inside the sample.
#' 
#' @export
SampleTaxoStatsModel <- function(sample_id=NULL, used_taxa=NULL, nb_unclassified=NULL, nb_validated=NULL, nb_dubious=NULL, nb_predicted=NULL) {
  body <- list(
    sample_id=sample_id,
    used_taxa=used_taxa,
    nb_unclassified=nb_unclassified,
    nb_validated=nb_validated,
    nb_dubious=nb_dubious,
    nb_predicted=nb_predicted
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
