# Automatically generated. Do not edit this file.
#' SampleModel
#' 
#' A list defining a SampleModel
#' 
#' @param sampleid \[integer, required\] The sample Id.
#' @param projid \[integer, required\] The project Id.
#' @param orig_id \[string, required\] Original sample ID from initial TSV load.
#' @param latitude \[number\] The latitude.
#' @param longitude \[number\] The longitude.
#' @param dataportal_descriptor \[string\] Dataportal descriptor.
#' @param free_columns \[list\] Free columns from sample mapping in project.
#' 
#' @export
SampleModel <- function(sampleid, projid, orig_id, latitude=NULL, longitude=NULL, dataportal_descriptor=NULL, free_columns=NULL) {
  body <- list(
    sampleid=sampleid,
    projid=projid,
    orig_id=orig_id,
    latitude=latitude,
    longitude=longitude,
    dataportal_descriptor=dataportal_descriptor,
    free_columns=free_columns
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
