# Automatically generated. Do not edit this file.
#' SciExportTypeEnum
#' 
#' A list defining a SciExportTypeEnum
#' 
#' 
#' @export
SciExportTypeEnum <- function() {
  body <- list(

  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
