# Automatically generated. Do not edit this file.
#' SciExportTypeEnum
#' 
#' A vector defining a SciExportTypeEnum
#' 
#' @format string containing ABO, CNC or BIV
#' 
#' @name SciExportTypeEnum
#' @export
NULL
