# Automatically generated. Do not edit this file.
#' Similarity Search Response
#' 
#' A list defining a Similarity Search Response
#' 
#' @param neighbor_ids \[vector of integer, required\] The list of similar objects IDs.
#' @param sim_scores \[vector of number, required\] The list of similarity scores, between 0 and 1. The higher the closer, e.g. 1 for the target_id itself.
#' @param message \[string\] A message to the user. If not 'Success' then some condition prevented the computation.
#' 
#' @export
SimilaritySearchRsp <- function(neighbor_ids, sim_scores, message=NULL) {
  body <- list(
    neighbor_ids=neighbor_ids,
    sim_scores=sim_scores,
    message=message
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
