# Automatically generated. Do not edit this file.
#' SimpleImportRsp
#' 
#' A list defining a SimpleImportRsp
#' 
#' @param job_id \[integer, required\] The job which was created for the run. 0 if called with dry_run option.
#' @param errors \[vector of string, required\] Validation errors, dry_run or not.
#' 
#' @export
SimpleImportRsp <- function(job_id, errors) {
  body <- list(
    job_id=job_id,
    errors=errors
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
