# Automatically generated. Do not edit this file.
#' SubsetRsp
#' 
#' A list defining a SubsetRsp
#' 
#' @param job_id \[integer, required\] The job created for this operation.
#' 
#' @export
SubsetRsp <- function(job_id) {
  body <- list(
    job_id=job_id
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
