# Automatically generated. Do not edit this file.
#' Subset request Model
#' 
#' A list defining a Subset request Model
#' 
#' @param filters \[object of type [ProjectFiltersDict]\] The filters to apply to project.
#' @param dest_prj_id \[integer, required\] The destination project ID.
#' @param group_type \[object of type [GroupDefinitions], required\] Define the groups in which to apply limits. C for categories, S for samples, A for acquisitions.
#' @param limit_type \[object of type [LimitMethods], required\] The type of limit_value: P for %, V for constant, both per group.
#' @param limit_value \[number, required\] Limit value, e.g. 20% or 5 per copepoda or 5% per sample.
#' 
#' @export
SubsetReq <- function(filters=NULL, dest_prj_id, group_type, limit_type, limit_value) {
  body <- list(
    filters=filters,
    dest_prj_id=dest_prj_id,
    group_type=group_type,
    limit_type=limit_type,
    limit_value=limit_value
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
