# Automatically generated. Do not edit this file.
#' SummaryExportGroupingEnum
#' 
#' A vector defining a SummaryExportGroupingEnum
#' 
#' @format string containing , S, A or P
#' 
#' @name SummaryExportGroupingEnum
NULL
