# Automatically generated. Do not edit this file.
#' SummaryExportGroupingEnum
#' 
#' A list defining a SummaryExportGroupingEnum
#' 
#' 
#' @export
SummaryExportGroupingEnum <- function() {
  body <- list(

  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
