# Automatically generated. Do not edit this file.
#' SummaryExportQuantitiesOptionsEnum
#' 
#' A list defining a SummaryExportQuantitiesOptionsEnum
#' 
#' 
#' @export
SummaryExportQuantitiesOptionsEnum <- function() {
  body <- list(

  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
