# Automatically generated. Do not edit this file.
#' SummaryExportQuantitiesOptionsEnum
#' 
#' A vector defining a SummaryExportQuantitiesOptionsEnum
#' 
#' @format string containing abundance, concentration or biovolume
#' 
#' @name SummaryExportQuantitiesOptionsEnum
#' @export
NULL
