# Automatically generated. Do not edit this file.
#' SummaryExportSumOptionsEnum
#' 
#' A list defining a SummaryExportSumOptionsEnum
#' 
#' 
#' @export
SummaryExportSumOptionsEnum <- function() {
  body <- list(

  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
