# Automatically generated. Do not edit this file.
#' Summary Export request Model
#' 
#' A list defining a Summary Export request Model
#' 
#' @param collection_id \[integer\] The Collection to export if requested.
#' @param project_id \[integer, string, required\] The project(int) or projects (str, project ids list) to export.
#' @param quantity \[object of type [SummaryExportQuantitiesOptionsEnum]\] The quantity to compute. Abundance is always possible.
#' @param summarise_by \[object of type [SummaryExportSumOptionsEnum]\] Computations aggregation level.
#' @param taxo_mapping \[list\] Mapping from present taxon (key) to output replacement one (value). Use a 0 replacement to _discard_ the present taxon.
#' @param formulae \[list\] Transitory: How to get values from DB free columns. Python syntax, prefixes are 'sam', 'ssm' and 'obj'.Variables used in computations are 'total_water_volume', 'subsample_coef' and 'individual_volume'
#' @param out_to_ftp \[boolean\] Copy result file to FTP area. Original file is still available.
#' 
#' @export
SummaryExportReq <- function(collection_id=NULL, project_id, quantity=NULL, summarise_by=NULL, taxo_mapping=NULL, formulae=NULL, out_to_ftp=NULL) {
  body <- list(
    collection_id=collection_id,
    project_id=project_id,
    quantity=quantity,
    summarise_by=summarise_by,
    taxo_mapping=taxo_mapping,
    formulae=formulae,
    out_to_ftp=out_to_ftp
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
