# Automatically generated. Do not edit this file.
#' SummaryExportSumOptionsEnum
#' 
#' A vector defining a SummaryExportSumOptionsEnum
#' 
#' @format string containing none, sample or acquisition
#' 
#' @name SummaryExportSumOptionsEnum
#' @export
NULL
