# Automatically generated. Do not edit this file.
#' TaxonUsageModel
#' 
#' A list defining a TaxonUsageModel
#' 
#' @param projid \[integer, required\] Project unique identifier.
#' @param title \[string, required\] Project's title.
#' @param nb_validated \[integer, required\] How many validated objects in this category in this project.
#' 
#' @export
TaxonUsageModel <- function(projid, title, nb_validated) {
  body <- list(
    projid=projid,
    title=title,
    nb_validated=nb_validated
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
