# Automatically generated. Do not edit this file.
#' TaxonCentral
#' 
#' A list defining a TaxonCentral
#' 
#' @param id \[integer, required\] The unique numeric id of the taxon.
#' @param parent_id \[integer\] The unique numeric id of the taxon parent.
#' @param name \[string, required\] The name of the taxon.
#' @param id_source \[string\] The source ID.
#' @param taxotype \[string, required\] The taxon type, 'M' for Morpho or 'P' for Phylo.
#' @param display_name \[string\] The display name of the taxon. It is suffixed in EcoTaxoServer with (Deprecated) when taxostatus is 'D'
#' @param lastupdate_datetime \[string\] Taxon last update. Date, with format YYYY-MM-DD hh:mm:ss.
#' @param id_instance \[integer\] The instance Id.
#' @param taxostatus \[string, required\] The taxon status, N for Not approved, A for Approved or D for Deprecated.
#' @param rename_to \[integer\] The advised replacement Name if the taxon is deprecated.
#' @param source_url \[string\] The source url.
#' @param source_desc \[string\] The source description.
#' @param creator_email \[string\] Email of the creator of the taxon.
#' @param creation_datetime \[string\] Taxon creation date. Date, with format YYYY-MM-DD hh:mm:ss.
#' @param nbrobj \[integer\] Number of objects in this category exactly.
#' @param nbrobjcum \[integer\] Number of objects in this category and descendant ones.
#' 
#' @export
TaxonCentral <- function(id, parent_id=NULL, name, id_source=NULL, taxotype, display_name=NULL, lastupdate_datetime=NULL, id_instance=NULL, taxostatus, rename_to=NULL, source_url=NULL, source_desc=NULL, creator_email=NULL, creation_datetime=NULL, nbrobj=NULL, nbrobjcum=NULL) {
  body <- list(
    id=id,
    parent_id=parent_id,
    name=name,
    id_source=id_source,
    taxotype=taxotype,
    display_name=display_name,
    lastupdate_datetime=lastupdate_datetime,
    id_instance=id_instance,
    taxostatus=taxostatus,
    rename_to=rename_to,
    source_url=source_url,
    source_desc=source_desc,
    creator_email=creator_email,
    creation_datetime=creation_datetime,
    nbrobj=nbrobj,
    nbrobjcum=nbrobjcum
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
