# Automatically generated. Do not edit this file.
#' TaxonomyTreeStatus
#' 
#' A list defining a TaxonomyTreeStatus
#' 
#' @param last_refresh \[string\] Taxonomy tree last refresh/sync from taxonomy server. Date, with format YYYY-MM-DDThh:mm:ss.
#' 
#' @export
TaxonomyTreeStatus <- function(last_refresh=NULL) {
  body <- list(
    last_refresh=last_refresh
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
