# Automatically generated. Do not edit this file.
#' UserModelWithRights
#' 
#' A list defining a UserModelWithRights
#' 
#' @param id \[integer, required\] The unique numeric id of this user.
#' @param email \[string, required\] User's email address, as text, used during registration.
#' @param password \[string\] Encrypted (or not) password.
#' @param name \[string, required\] User's full name, as text.
#' @param organisation \[string\] User's organisation name, as text.
#' @param active \[boolean\] Whether the user is still active.
#' @param country \[string\] The country name, as text (but chosen in a consistent list).
#' @param usercreationdate \[string\] The date of creation of the user, as text formatted according to the ISO 8601 standard.
#' @param usercreationreason \[string\] Paragraph describing the usage of EcoTaxa made by the user.
#' @param can_do \[vector of integer\] List of User's allowed actions : 1 create a project, 2 administrate the app, 3 administrate users, 4 create taxon.
#' @param last_used_projects \[vector of \] List of User's last used projects.
#' 
#' @export
UserModelWithRights <- function(id, email, password=NULL, name, organisation=NULL, active=NULL, country=NULL, usercreationdate=NULL, usercreationreason=NULL, can_do=NULL, last_used_projects=NULL) {
  body <- list(
    id=id,
    email=email,
    password=password,
    name=name,
    organisation=organisation,
    active=active,
    country=country,
    usercreationdate=usercreationdate,
    usercreationreason=usercreationreason,
    can_do=can_do,
    last_used_projects=last_used_projects
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
