# Automatically generated. Do not edit this file.
#' UserActivateReq
#' 
#' A list defining a UserActivateReq
#' 
#' @param token \[string\] token when the user is not an admin and must confirm the email. 
#' @param reason \[string\] status,optional users administrator comment related to the status. 
#' @param password \[string\] Existing user can modify own email and must confirm it with token and password when email confirmation is on. 
#' 
#' @export
UserActivateReq <- function(token=NULL, reason=NULL, password=NULL) {
  body <- list(
    token=token,
    reason=reason,
    password=password
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
