# Automatically generated. Do not edit this file.
#' UserActivity
#' 
#' A list defining a UserActivity
#' 
#' @param id \[integer\] Id
#' @param nb_actions \[integer\] Nb Actions
#' @param last_annot \[string\] Last Annot
#' 
#' @export
UserActivity <- function(id=NULL, nb_actions=NULL, last_annot=NULL) {
  body <- list(
    id=id,
    nb_actions=nb_actions,
    last_annot=last_annot
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
