# Automatically generated. Do not edit this file.
#' ValidationError
#' 
#' A list defining a ValidationError
#' 
#' @param loc \[vector of string, required\] Location
#' @param msg \[string, required\] Message
#' @param type \[string, required\] Error Type
#' 
#' @export
ValidationError <- function(loc, msg, type) {
  body <- list(
    loc=loc,
    msg=msg,
    type=type
  )
  body[sapply(body, is.null)] <- NULL
  return(body)
}
